version: '3'
services:
  react-app:
    
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "3001:80"  
    
    restart: always
    
    environment:
      - NODE_ENV=production
